/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundCard: typeof import('./../components/BackgroundCard.vue')['default']
    Bar: typeof import('./../components/Bar.vue')['default']
    Bar2: typeof import('./../components/Bar2.vue')['default']
    Bar3: typeof import('./../components/Bar3.vue')['default']
    ChartCard: typeof import('./../components/ChartCard.vue')['default']
    CommonBar: typeof import('./../components/CommonBar.vue')['default']
    CommonBasicBar: typeof import('./../components/CommonBasicBar.vue')['default']
    CommonPie: typeof import('./../components/CommonPie.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    MyE: typeof import('./../components/MyE.vue')['default']
    NumberCard: typeof import('./../components/NumberCard.vue')['default']
    PentagonScore: typeof import('./../components/PentagonScore.vue')['default']
    Pie: typeof import('./../components/Pie.vue')['default']
    Progress: typeof import('./../components/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleCard: typeof import('./../components/TitleCard.vue')['default']
  }
}
