/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundCard: typeof import('./../components/BackgroundCard.vue')['default']
    Bar: typeof import('./../components/Bar.vue')['default']
    ChartCard: typeof import('./../components/ChartCard.vue')['default']
    CommonBar: typeof import('./../components/CommonBar.vue')['default']
    CommonBasicBar: typeof import('./../components/CommonBasicBar.vue')['default']
    CommonPie: typeof import('./../components/CommonPie.vue')['default']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    Pie: typeof import('./../components/Pie.vue')['default']
    Progress: typeof import('./../components/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleCard: typeof import('./../components/TitleCard.vue')['default']
  }
}
